### ISSUE TITLE
Installation of Gate V9.0 fails in the last step  

### ISSUE THREAD

**Issue by xiezhaoheng** [Alxaline/Easy-GATE-Installation#2]
Thanks for sharing your script in github for easy Gate installation. It is a great contribution to this community. Unfortunately, when I follow your instruction and install the GATEv9.0, the installation of Gate V9.0 fails in the last step  (see the following message). The root, ITK, and Geant4 look fine. Have you ever meet the same issue?
'’
[ 99%] Linking CXX executable GateDigit_singles_sorter
[ 99%] Linking CXX executable GateDigit_hits_digitizer
[ 99%] Linking CXX executable GateDigit_coincidence_processor
/usr/bin/ld: cannot find -lHist
/usr/bin/ld: cannot find -lGraf
/usr/bin/ld: cannot find -lGraf3d
/usr/bin/ld: cannot find -lGpad
/usr/bin/ld: cannot find -lTreePlayer
/usr/bin/ld: cannot find -lPostscript
/usr/bin/ld: cannot find -lROOTDataFrame
collect2: error: ld returned 1 exit status
CMakeFiles/GateDigit_singles_sorter.dir/build.make:1656: recipe for target 'GateDigit_singles_sorter' failed
make[2]: *** [GateDigit_singles_sorter] Error 1
CMakeFiles/Makefile2:118: recipe for target 'CMakeFiles/GateDigit_singles_sorter.dir/all' failed
make[1]: *** [CMakeFiles/GateDigit_singles_sorter.dir/all] Error 2
##############
The same error for GateDigit_coincidence_processor  and GateDigit_hits_digitizer:
##############
make[2]: *** [GateDigit_coincidence_processor] Error 1
CMakeFiles/Makefile2:196: recipe for target 'CMakeFiles/GateDigit_coincidence_processor.dir/all' failed
make[1]: *** [CMakeFiles/GateDigit_coincidence_processor.dir/all] Error 2
##############
CMakeFiles/GateDigit_hits_digitizer.dir/build.make:1656: recipe for target 'GateDigit_hits_digitizer' failed
make[2]: *** [GateDigit_hits_digitizer] Error 1
CMakeFiles/Makefile2:144: recipe for target 'CMakeFiles/GateDigit_hits_digitizer.dir/all' failed
make[1]: *** [CMakeFiles/GateDigit_hits_digitizer.dir/all] Error 2
##############
’‘
BTW, my system is Ubuntu 16.04, CMake version is 3.20.

**Comment by Alxaline** [comment]
hello @xiezhaoheng 

Can you show me your environment variables?

`printenv`

Best regards,

**Comment by xiezhaoheng** [comment]
**Thanks for your reply. The following part is the environment variables:**

''
G4LEVELGAMMADATA=/usr/local/GATE/geant4.10.06.p01-install/share/Geant4-10.6.1/data/PhotonEvaporation5.5
XDG_VTNR=7
MANPATH=/usr/local/GATE/root-6.20.04-build/man:/home/wayne/anaconda2/envs/zhxiegate90/share/man:/home/wayne/anaconda2/man:/usr/local/man:/usr/local/share/man:/usr/share/man
XDG_SESSION_ID=c2
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/wayne
CLUTTER_IM_MODULE=xim
DBUS_STARTER_ADDRESS=unix:abstract=/tmp/dbus-xk5BQCjkwK,guid=15cd47b5e292635f516e8eee6110c667
GPG_AGENT_INFO=/home/wayne/.gnupg/S.gpg-agent:0:1
TERM=xterm-256color
VTE_VERSION=4205
XDG_MENU_PREFIX=gnome-
SHELL=/bin/bash
CONDA_SHLVL=1
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
CONDA_PROMPT_MODIFIER=
WINDOWID=77594634
OLDPWD=/usr/local/GATE/Gate-9.0-build
UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1002/7934
GNOME_KEYRING_CONTROL=
GTK_MODULES=gail:atk-bridge:unity-gtk-module
G4LEDATA=/usr/local/GATE/geant4.10.06.p01-install/share/Geant4-10.6.1/data/G4EMLOW7.9.1
USER=wayne
LD_LIBRARY_PATH=/usr/local/GATE/geant4.10.06.p01-install/lib:/usr/local/GATE/root-6.20.04-build/lib:/usr/local/GATE/geant4.10.06.p01-install/lib:/usr/local/GATE/geant4.10.06.p01-install/lib:/usr/local/GATE/geant4.10.06.p01-install/lib
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
QT_ACCESSIBILITY=1
CONDA_EXE=/home/wayne/anaconda2/bin/conda
UNITY_HAS_3D_SUPPORT=true
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
G4NEUTRONHPDATA=/usr/local/GATE/geant4.10.06.p01-install/share/Geant4-10.6.1/data/G4NDL4.6
SSH_AUTH_SOCK=/run/user/1002/keyring/ssh
G4ENSDFSTATEDATA=/usr/local/GATE/geant4.10.06.p01-install/share/Geant4-10.6.1/data/G4ENSDFSTATE2.2
G4RADIOACTIVEDATA=/usr/local/GATE/geant4.10.06.p01-install/share/Geant4-10.6.1/data/RadioactiveDecay5.4
LIBPATH=/usr/local/GATE/root-6.20.04-build/lib
SESSION_MANAGER=local/COE-BME-JQ-ZX:@/tmp/.ICE-unix/8201,unix/COE-BME-JQ-ZX:/tmp/.ICE-unix/8201
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
G4ABLADATA=/usr/local/GATE/geant4.10.06.p01-install/share/Geant4-10.6.1/data/G4ABLA3.1
JUPYTER_PATH=/usr/local/GATE/root-6.20.04-build/etc/notebook
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
UNITY_DEFAULT_PROFILE=unity
DESKTOP_SESSION=ubuntu
PATH=/usr/local/GATE/geant4.10.06.p01-install/bin:/usr/local/GATE/root-6.20.04-build/bin:/usr/local/GATE/geant4.10.06.p01-install/bin:/usr/local/GATE/geant4.10.06.p01-install/bin:/usr/local/GATE/geant4.10.06.p01-install/bin:/home/wayne/anaconda2/bin:/home/wayne/bin:/home/wayne/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/GATE/Gate-9.0-install/bin:/usr/local/GATE/Gate-9.0-install/bin
QT_IM_MODULE=fcitx
QT_QPA_PLATFORMTHEME=appmenu-qt5
CONDA_PREFIX=/home/wayne/anaconda2
G4PIIDATA=/usr/local/GATE/geant4.10.06.p01-install/share/Geant4-10.6.1/data/G4PII1.3
XDG_SESSION_TYPE=x11
PWD=/usr/local/GATE
JOB=xsession-init
XMODIFIERS=@im
G4PARTICLEXSDATA=/usr/local/GATE/geant4.10.06.p01-install/share/Geant4-10.6.1/data/G4PARTICLEXS2.1
GNOME_KEYRING_PID=
LANG=en_US.UTF-8
CLING_STANDARD_PCH=none
GDM_LANG=en_US
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
COMPIZ_CONFIG_PROFILE=ubuntu
IM_CONFIG_PHASE=1
G4SAIDXSDATA=/usr/local/GATE/geant4.10.06.p01-install/share/Geant4-10.6.1/data/G4SAIDDATA2.0
GDMSESSION=ubuntu
ROOTSYS=/usr/local/GATE/root-6.20.04-build
SESSIONTYPE=gnome-session
DBUS_STARTER_BUS_TYPE=session
GTK2_MODULES=overlay-scrollbar
SHLVL=1
HOME=/home/wayne
XDG_SEAT=seat0
G4REALSURFACEDATA=/usr/local/GATE/geant4.10.06.p01-install/share/Geant4-10.6.1/data/RealSurface2.1.1
LANGUAGE=en_US
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
DYLD_LIBRARY_PATH=/usr/local/GATE/root-6.20.04-build/lib
UPSTART_INSTANCE=
PYTHONPATH=/usr/local/GATE/root-6.20.04-build/lib
CONDA_PYTHON_EXE=/home/wayne/anaconda2/bin/python
UPSTART_EVENTS=starting
XDG_SESSION_DESKTOP=ubuntu
LOGNAME=wayne
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop
QT4_IM_MODULE=fcitx
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-xk5BQCjkwK,guid=15cd47b5e292635f516e8eee6110c667
CONDA_DEFAULT_ENV=base
LESSOPEN=| /usr/bin/lesspipe %s
SHLIB_PATH=/usr/local/GATE/root-6.20.04-build/lib
INSTANCE=
UPSTART_JOB=dbus
CMAKE_PREFIX_PATH=/usr/local/GATE/root-6.20.04-build
DBUS_DEBUG_OUTPUT=1
XDG_RUNTIME_DIR=/run/user/1002
DISPLAY=:0
XDG_CURRENT_DESKTOP=Unity
GTK_IM_MODULE=fcitx
G4INCLDATA=/usr/local/GATE/geant4.10.06.p01-install/share/Geant4-10.6.1/data/G4INCL1.0
LESSCLOSE=/usr/bin/lesspipe %s %s
XAUTHORITY=/home/wayne/.Xauthority
_=/usr/bin/printenv
''
It seems I miss some  (lib) files in the root. However, my root installation is successful** 
''
[100%] Linking CXX executable ../../bin/hist2workspace
[100%] Built target hist2workspace
Installation of root-6.20.04 done.
''

**Comment by Alxaline** [comment]
Hello can you try to change the PATH variable with (not preprending anaconda):

`export PATH=/usr/local/GATE/geant4.10.06.p01-install/bin:/usr/local/GATE/root-6.20.04-build/bin:/usr/local/GATE/geant4.10.06.p01-install/bin:/usr/local/GATE/geant4.10.06.p01-install/bin:/usr/local/GATE/geant4.10.06.p01-install/bin:/home/wayne/bin:/home/wayne/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/GATE/Gate-9.0-install/bin:/usr/local/GATE/Gate-9.0-install/bin:/home/wayne/anaconda2/bin`

Best regards,

**Comment by Alxaline** [comment]
Issue is closed due to inactivity.

Feel free to re-open.
